version: "3.9"

services:
  toxicity-app:
    build: .
    container_name: toxicity_app
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run_pipeline.py
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
