stages:
  train:
    cmd: python train_models.py
    deps:
    - data/bbb_logbb
    - data/oct2
    - data/vd
    - train_models.py
    outs:
    - models/bbb_xgb_model.pkl
    - models/carcinogenicity_xgb_model.pkl
    - models/generaltox_xgb_model.pkl
    - models/ld50_xgb_model.pkl
    - models/oct2_xgb_model.pkl
    - models/vd_xgb_model.pkl
