name: Code CI Pipeline

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint-test-docker:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff pytest httpx

      - name: Run Black
        run: black . --check

      - name: Run Ruff
        run: ruff . --output-format=github

      - name: Run Pytest
        run: pytest tests/

      - name: Build Docker image
        run: docker build -t toxicity-api .

      - name: Run FastAPI smoke test
        run: |
          nohup uvicorn api.main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl -f http://localhost:8000/docs || exit 1
